# 3.2 Guia - Numpy

In [17]:
import numpy as np

In [18]:
# Gerando 1 milhão de Registros
Estresando_Numpy_01 = np.arange(1000000)
# Gerando 10 milhões de Registros
Estresando_Numpy_02 = np.arange(10000000)
# Gerando 50 milhões de Registros
Estresando_Numpy_03 = np.arange(50000000)
# Gerando 100 milhões de Registros
Estresando_Numpy_04 = np.arange(100000000)

# Verificando o Array
print('Tamanho do Array:', len(Estresando_Numpy_01))
print('Tamanho do Array:', len(Estresando_Numpy_02))
print('Tamanho do Array:', len(Estresando_Numpy_03))
print('Tamanho do Array:', len(Estresando_Numpy_04))

Tamanho do Array: 1000000
Tamanho do Array: 10000000
Tamanho do Array: 50000000
Tamanho do Array: 100000000


In [19]:
# Verificando o Array
%time for i in Estresando_Numpy_01: pass

Wall time: 282 ms


In [20]:
# Verificando o Array
%time for i in Estresando_Numpy_02: pass

Wall time: 2.14 s


In [21]:
# Verificando o Array
%time for i in Estresando_Numpy_03: pass

Wall time: 9.35 s


In [22]:
# Verificando o Array
%time for i in Estresando_Numpy_04: pass

Wall time: 15.1 s


In [23]:
# Versão
print(np.__version__)

1.19.2


In [24]:
# Criando matriz com uma dimnesão
Array = np.array([10,20,30,40,50])
Array

array([10, 20, 30, 40, 50])

In [25]:
# Verificando o Tipo
print( type(Array))

<class 'numpy.ndarray'>


In [26]:
# Criando Trupla usando 1 dimensão
Tupla_Array = np.array((10,20,30,40,50))
Tupla_Array

array([10, 20, 30, 40, 50])

In [27]:
# Criando uma Matriz com 0 dimensões
Matriz_Zero = np.array(11)
Matriz_Zero

array(11)

In [28]:
# Matriz com duas Dimensões
Matriz_Duas_Dimensoes = np.array([
    [10,9,8,7,6],
    [5,4,3,2,1,0]
])

print(Matriz_Duas_Dimensoes)

[list([10, 9, 8, 7, 6]) list([5, 4, 3, 2, 1, 0])]


<ipython-input-28-909d6dc3b3da>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Matriz_Duas_Dimensoes = np.array([


In [29]:
# Matriz com três Dimensões
Matriz_Tres_Dimensoes=np.array([
    [15,14,13,12,11],
    [10,9,8,7,6],
    [5,4,3,2,1,0]
])

print(Matriz_Tres_Dimensoes)

[list([15, 14, 13, 12, 11]) list([10, 9, 8, 7, 6])
 list([5, 4, 3, 2, 1, 0])]


<ipython-input-29-073f985c7399>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Matriz_Tres_Dimensoes=np.array([


In [30]:
# Verificando a quantidade de Dimensões em uma Matriz
print('Qtas Dimensões no "Matriz_Zero":', Matriz_Zero.ndim,'\n')
print('Qtas Dimensões no "Array":', Array.ndim,'\n')
print('Qtas Dimensões no "Matriz_Duas_Dimensoes":', Matriz_Duas_Dimensoes.ndim,'\n')
print('Qtas Dimensões no "Matriz_Tres_Dimensoes":', Matriz_Tres_Dimensoes.ndim,'\n')

Qtas Dimensões no "Matriz_Zero": 0 

Qtas Dimensões no "Array": 1 

Qtas Dimensões no "Matriz_Duas_Dimensoes": 1 

Qtas Dimensões no "Matriz_Tres_Dimensoes": 1 



In [34]:
# Criar uma mariz e definir a quantidade de dimensões
Definindo_Numeros_Dimensoes = np.array(
    [999,998,997,996,995],
    ndmin=10
)
print(Definindo_Numeros_Dimensoes, '\n')
print('Dimensões:', Definindo_Numeros_Dimensoes.ndim)

[[[[[[[[[[999 998 997 996 995]]]]]]]]]] 

Dimensões: 10


In [35]:
# Podemos acessar um valor atras da posição

Array=np.array([10,20,30,40,50])

print('Acessando posição 1:',Array[0])
print('Acessando a ultima posição:',Array[-1])
print('Acessando a penultima posição:',Array[-2:-1])
print('Acessando um range posição:',Array[0:3])

Acessando posição 1: 10
Acessando a ultima posição: 50
Acessando a penultima posição: [40]
Acessando um range posição: [10 20 30]


In [37]:
# Operações matematicas
Soma = Array[0]+Array[1]
Subtração = Array[0]-Array[1]
Divisão = Array[0] / Array[1]
Multiplicação = Array[0]*Array[1]
Resto=Array[0]%Array[1]
Expoente=Array[0]**Array[1]

# Podemos fazer condições
Condição_Igual = Array[0] == Array[1]
Condição_Maior = Array[0] > Array[1]
Condição_Menor = Array[0] < Array[1]
Condição_Maior_Igual = Array[0] >= Array[1]
Condição_Menor_Igual = Array[0] <= Array[1]
Diferente = Array[0] != Array[1]

print('Operações Matematicas Resultado \o/')
print('Soma: ',Soma)
print('Subtração: ',Subtração)
print('Divisão: ',Divisão)
print('Multiplicação: ',Multiplicação)
print('Resto: ',Resto)
print('Expoente: ',Expoente)

print('\n','Condições Resultados \o/')
print('Condição_Igual: ',Condição_Igual)
print('Condição_Maior_Igual: ',Condição_Maior_Igual)
print('Condição_Menor: ',Condição_Menor)
print('Condição_Menor_Igual: ',Condição_Menor_Igual)
print('Diferente: ',Diferente)

Operações Matematicas Resultado \o/
Soma:  30
Subtração:  -10
Divisão:  0.5
Multiplicação:  200
Resto:  10
Expoente:  1661992960

 Condições Resultados \o/
Condição_Igual:  False
Condição_Maior_Igual:  False
Condição_Menor:  True
Condição_Menor_Igual:  True
Diferente:  True


In [38]:
# Acessando uma Matriz com 2 Dimensões
Matriz_Dois_Dimensoes = np.array([
    [15,14,13,12,11],
    [10,9,8,7,6]
])

print('Acessando a 2º Dimensão, Posição numero 2')
print(Matriz_Dois_Dimensoes[1,1])

Acessando a 2º Dimensão, Posição numero 2
9


In [39]:
# Tipos de Formatos de Campo
Inteiro = np.array([10,20,30,40,50])
Textos = np.array(['Uva','Pera','Limão'])
Fragmento = np.array([10,20,30,40,50],dtype='S')
Flutuante = np.array([10,20,30,40,50],dtype='f')

print(Inteiro.dtype)
print(Textos.dtype)
print(Fragmento.dtype)
print(Flutuante.dtype)

int32
<U5
|S2
float32


In [40]:
# Podemos Converter o formato de matriz para um outro tipo
Inteiro = np.array([10,20,30,40,50])
Converter_Booleano = Inteiro.astype('bool')
Converter_Quebrado = Inteiro.astype('f')

print(Inteiro.dtype)
print(Converter_Booleano.dtype)
print(Converter_Quebrado.dtype)

int32
bool
float32


In [41]:
# Shape
Matriz_Tres_Dimensoes.shape

(3,)

In [43]:
# Remodelar a Matriz

Matriz_Uma_Dimensão = np.array([1,2,3,4,5,6,7,
                               8,9,10,11,12])
Remodelando_01 = Matriz_Uma_Dimensão.reshape(4,3)
Remodelando_02 = Matriz_Uma_Dimensão.reshape(2,6)
print('1º Matriz: ','\n', Remodelando_01, '\n')
print('1º Matriz: ','\n', Remodelando_02)

1º Matriz:  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

1º Matriz:  
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [44]:
# Percorrendo uma Matriz

Matriz_Uma_Dimensão = np.array([1,2,3,4,5,6,7,
                               8,9,10,11,12])
for Percorrendo in Matriz_Uma_Dimensão:
    print(Percorrendo)

1
2
3
4
5
6
7
8
9
10
11
12


In [46]:
# Percorrendo uma matriz de 2 Dimensões
Matriz_Dois_Dimensoes = np.array([
    [15,14,13,12,11],
    [10,9,8,7,6,5]
])

for Percorrendo in Matriz_Dois_Dimensoes:
    for Posicao in Percorrendo:
        print(Posicao)

15
14
13
12
11
10
9
8
7
6
5


<ipython-input-46-7e6fcd4a2e2c>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Matriz_Dois_Dimensoes = np.array([


In [47]:
# Percorrendo uma Matriz e Enumerando a posição
Matriz_Uma_Dimensão = np.array([1,2,3,4,5,6,7,
                               8,9,10,11,12])
for Posicao, Percorrendo in np.ndenumerate(Matriz_Uma_Dimensão):
    print(Posicao, Percorrendo)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [48]:
# Juntar 2 Matrizes em uma unica
Array_01 = np.array([1,2,3])
Array_02 = np.array([4,5,6])

#Exemplo_01
Juntando_01 = np.concatenate((Array_02,Array_01))
#Exemplo_02
Juntando_02 = np.concatenate((Array_01,Array_02,Array_01))
#Exemplo_03
Juntando_03 = np.concatenate((Array_01*2,
                              Array_02*Array_01,
                              Array_01-Array_02))
print(Juntando_01,'\n')
print(Juntando_02,'\n')
print(Juntando_03,'\n')

[4 5 6 1 2 3] 

[1 2 3 4 5 6 1 2 3] 

[ 2  4  6  4 10 18 -3 -3 -3] 



In [49]:
# Quebrando/Fatiando uma Matriz

Array = np.array([1,2,3,4,5,6])
Quebrando_Array_em3 = np.array_split(Array,3)
Quebrando_Array_em4 = np.array_split(Array,4)
Quebrando_Array_em2 = np.array_split(Array,2)

print(Quebrando_Array_em3,'\n')
print(Quebrando_Array_em4,'\n')
print(Quebrando_Array_em2)

[array([1, 2]), array([3, 4]), array([5, 6])] 

[array([1, 2]), array([3, 4]), array([5]), array([6])] 

[array([1, 2, 3]), array([4, 5, 6])]


In [51]:
# Outro metodo para quebrar

Matriz = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12],
                 [13,14,15],
                 [16,17,18]])

Quebrando = np.hsplit(Matriz,3)
print(Quebrando)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [52]:
# Procurando valores em uma Matriz

Array = np.array([1,2,3,4,5,6])

Procurando_01 = np.where(Array==2)
Procurando_02 = np.where(Array>2)
Procurando_03 = np.where(Array==True)

print(Procurando_01,'\n')
print(Procurando_02,'\n')
print(Procurando_03)

(array([1], dtype=int64),) 

(array([2, 3, 4, 5], dtype=int64),) 

(array([0], dtype=int64),)


In [53]:
# Ordenando uma Matriz
Array = np.array([4,10,6,11,1,2])
Matriz_Duas_Dimensoes = np.array([
    [10,9,8,7,6],
    [5,4,3,2,1,0]
])
Ordenando_01 = np.sort(Array)
Ordenando_02 = np.sort(Matriz_Duas_Dimensoes)

print(Ordenando_01,'\n')
print(Ordenando_02,'\n')

[ 1  2  4  6 10 11] 

[list([5, 4, 3, 2, 1, 0]) list([10, 9, 8, 7, 6])] 



<ipython-input-53-a597d752a4ca>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  Matriz_Duas_Dimensoes = np.array([
